server:
  port: 8004
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bd_productos
    username: root
    password: Gonzalocuevas-1998
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka